package com.car.model;

import java.io.Serializable;

/**
 * ShoppingList 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Shoppinglist implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** carid. */
	private Integer carid;

	/** prince. */
	private Integer prince;

	/** yanse. */
	private String yanse;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public Shoppinglist() {
	}

	/**
	 * carid 傪愝掕偟傑偡.
	 * 
	 * @param carid
	 *            carid
	 */
	public void setCarid(Integer carid) {
		this.carid = carid;
	}

	/**
	 * carid 傪庢摼偟傑偡.
	 * 
	 * @return carid
	 */
	public Integer getCarid() {
		return this.carid;
	}

	/**
	 * prince 傪愝掕偟傑偡.
	 * 
	 * @param prince
	 *            prince
	 */
	public void setPrince(Integer prince) {
		this.prince = prince;
	}

	/**
	 * prince 傪庢摼偟傑偡.
	 * 
	 * @return prince
	 */
	public Integer getPrince() {
		return this.prince;
	}

	/**
	 * yanse 傪愝掕偟傑偡.
	 * 
	 * @param yanse
	 *            yanse
	 */
	public void setYanse(String yanse) {
		this.yanse = yanse;
	}

	/**
	 * yanse 傪庢摼偟傑偡.
	 * 
	 * @return yanse
	 */
	public String getYanse() {
		return this.yanse;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((carid == null) ? 0 : carid.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Shoppinglist other = (Shoppinglist) obj;
		if (carid == null) {
			if (other.carid != null) {
				return false;
			}
		} else if (!carid.equals(other.carid)) {
			return false;
		}

		return true;
	}

}
